"""
Generated Venice AI API Pydantic Models

This package contains comprehensive Pydantic models for all Venice AI API endpoints.
These models provide full type safety, validation, and auto-completion for Python clients.

The models are organized by API category:
- base: Shared types and base models (includes error response models)
- chat: Chat completion models
- images: Image generation models
- models: Model listing and metadata models
- api_keys: API key management models
- billing: Billing and usage models
- audio: Audio/TTS models
- embeddings: Text embedding models
- characters: Character persona models
- web3: Web3 authentication models
- requests: Request models for all API endpoints
"""

# Import all models from sub-modules - explicit imports to avoid F403/F405 errors
from .api_keys import (
    ApiKey,
    ApiKeyDetailsResponse,
    ApiKeysListResponse,
    ApiKeyUsage,
    ApiTier,
    Balances,
    ConsumptionLimits,
    CreateApiKeyResponse,
    CreatedApiKey,
    DeleteApiKeyResponse,
    ModelRateLimit,
    RateLimit,
    RateLimitLogEntry,
    RateLimitLogsResponse,
    RateLimitsData,
    RateLimitsResponse,
    RateLimitType,
    TrailingSevenDaysUsage,
)
from .audio import (
    AudioResponse,
    AudioTranscriptionResponse,
    ClonedVoice,
    TranscriptionWord,
    VoiceDetail,
    VoiceList,
)
from .augment import (
    AugmentScrapeRequest,
    AugmentScrapeResponse,
    AugmentSearchRequest,
    AugmentSearchResponse,
    AugmentSearchResult,
    AugmentTextParserResponse,
)
from .base import (
    BaseListResponse,
    BaseSuccessResponse,
    DetailedError,
    StandardError,
    TimingInfo,
    UsageData,
)
from .billing import (
    BillingBalanceResponse,
    BillingUsageEntry,
    BillingUsageHistoryResponse,
    InferenceDetails,
    UsageAnalyticsByDate,
    UsageAnalyticsByKey,
    UsageAnalyticsByModel,
    UsageAnalyticsModelBreakdown,
    UsageAnalyticsQueryParams,
    UsageAnalyticsResponse,
)
from .characters import (
    Character,
    CharacterResponse,
    CharacterReview,
    CharacterReviewsPagination,
    CharacterReviewsResponse,
    CharacterReviewsSummary,
    CharactersListResponse,
    CharacterStats,
)
from .chat import (
    ChatChoice,
    ChatCompletionResponse,
    ChatMessage,
    ChatUsage,
    LogProbToken,
    ToolCall,
    ToolCallFunction,
)
from .common import (
    CompletionTokensDetails,
    ErrorDetails,
    PromptTokensDetails,
    WebSearchCitation,
)
from .crypto import (
    BatchJsonRpcResponse,
    CryptoNetworksResponse,
    JsonRpcError,
    JsonRpcRequest,
    JsonRpcResponse,
)
from .embeddings import (
    EmbeddingObject,
    EmbeddingsResponse,
    EmbeddingUsage,
)
from .images import (
    ImageGenerationResponse,
    ImageStylesResponse,
    SimpleImageData,
    SimpleImageGenerationResponse,
)
from .models import (
    ASRModelPricing,
    AsrModelSpec,
    AudioModelPricing,
    EmbeddingModelSpec,
    ImageModelConstraints,
    ImageModelPricing,
    ImageModelSpec,
    InpaintModelConstraints,
    InpaintModelPricing,
    InpaintModelSpec,
    LLMModelPricing,
    ModelCapabilities,
    ModelCompatibilityResponse,
    ModelConstraints,
    ModelDeprecation,
    ModelPricing,
    ModelResponse,
    ModelsListResponse,
    ModelSpec,
    ModelTraitsResponse,
    MusicModelPricing,
    MusicModelSpec,
    PricingTier,
    StepsConstraint,
    TemperatureConstraint,
    TextModelConstraints,
    TextModelSpec,
    TopPConstraint,
    TtsModelSpec,
    UpscaleModelSpec,
    UpscalePricing,
    VideoModelConstraints,
    VideoModelSpec,
    VideoResolutionPricing,
)
from .music import (
    MusicCompletedStatus,
    MusicCompleteResponse,
    MusicFailedStatus,
    MusicProcessingStatus,
    MusicQueueResponse,
    MusicQuoteResponse,
    MusicRetrieveResponse,
)
from .requests import (
    AssistantMessage,
    # Audio models
    AudioSpeechRequest,
    AudioTranscriptionRequest,
    BillingUsageHistoryQueryParams,
    ChatCompletionRequest,
    ChatMessageParam,
    # API key models
    ConsumptionLimit,
    CreateApiKeyRequest,
    DateRangeParams,
    DeleteApiKeyQueryParams,
    DeveloperMessage,
    # Embeddings models
    EmbeddingsRequest,
    FileContent,
    FileObject,
    ImageBackgroundRemoveRequest,
    ImageContent,
    ImageEditRequest,
    # Image generation models
    ImageGenerationRequest,
    ImageMultiEditRequest,
    ImageUpscaleRequest,
    ImageUrl,
    JSONObjectFormat,
    JSONSchemaFormat,
    # Query parameter models
    ModelsQueryParams,
    ModelTraitsQueryParams,
    # Music request models
    MusicCompleteRequest,
    MusicQueueRequest,
    MusicQuoteRequest,
    MusicRetrieveRequest,
    # Utility models
    PaginationParams,
    # Reasoning controls
    ReasoningConfig,
    ReasoningEffortLevel,
    ReasoningSummary,
    # Responses API (Alpha)
    ResponsesRequest,
    SeedanceConsents,
    SimpleImageGenerationRequest,
    SpecificToolChoice,
    StreamOptions,
    StyleReference,
    SystemMessage,
    # Chat completion models
    TextContent,
    TextResponseFormat,
    Tool,
    ToolChoiceFunction,
    ToolFunction,
    ToolMessage,
    UpdateApiKeyRequest,
    UserMessage,
    VeniceParameters,
    VideoCompleteRequest,
    VideoConsents,
    VideoImageToVideoRequest,
    VideoQueueRequest,
    VideoQuoteRequest,
    # Video request models
    VideoRequestBase,
    VideoRetrieveRequest,
    VideoTextToVideoRequest,
    VideoTranscriptionRequest,
    Web3CreateApiKeyRequest,
)
from .responses import (
    ResponsesError,
    ResponsesFunctionCallOutput,
    ResponsesMessageOutput,
    ResponsesOutputItem,
    ResponsesOutputText,
    ResponsesReasoningOutput,
    ResponsesResponse,
    ResponsesStreamEvent,
    ResponsesUnknownOutput,
    ResponsesUsage,
    ResponsesUsageInputDetails,
    ResponsesUsageOutputDetails,
    ResponsesWebSearchCallOutput,
)
from .streaming import (
    ChatCompletionChoiceLogprobs,
    ChatCompletionChunk,
    ChatCompletionChunkChoice,
    ChatCompletionChunkChoiceDelta,
    ChatCompletionChunkToolCall,
    ChatCompletionChunkToolCallFunction,
    ChatCompletionTokenLogprob,
    ChatCompletionTopLogprob,
    ChunkModelFactory,
)
from .video import (
    VideoCompletedStatus,
    VideoCompleteResponse,
    VideoFailedStatus,
    VideoProcessingStatus,
    VideoQueueResponse,
    VideoQuoteResponse,
    VideoRetrieveResponse,
    VideoTranscriptionResponse,
)
from .web3 import (
    Web3ApiKeyResponse,
    Web3TokenData,
    Web3TokenResponse,
)
from .x402 import (
    X402BalanceData,
    X402BalanceResponse,
    X402TopUpData,
    X402TopUpResponse,
    X402Transaction,
    X402TransactionsData,
    X402TransactionsPagination,
    X402TransactionsResponse,
)

# Consolidated __all__ list with all exported symbols
__all__ = [
    # From common module
    "WebSearchCitation",
    "ErrorDetails",
    "PromptTokensDetails",
    "CompletionTokensDetails",
    # From base module
    "StandardError",
    "DetailedError",
    "TimingInfo",
    "UsageData",
    "BaseListResponse",
    "BaseSuccessResponse",
    # From chat module
    "ToolCallFunction",
    "ToolCall",
    "ChatMessage",
    "LogProbToken",
    "ChatChoice",
    "ChatUsage",
    "ChatCompletionResponse",
    # From images module
    "ImageGenerationResponse",
    "SimpleImageData",
    "SimpleImageGenerationResponse",
    "ImageStylesResponse",
    # From models module
    "ModelCapabilities",
    "TemperatureConstraint",
    "TopPConstraint",
    "StepsConstraint",
    "TextModelConstraints",
    "ImageModelConstraints",
    "InpaintModelConstraints",
    "VideoModelConstraints",
    "PricingTier",
    "LLMModelPricing",
    "UpscalePricing",
    "ImageModelPricing",
    "AudioModelPricing",
    "VideoResolutionPricing",
    "InpaintModelPricing",
    "ASRModelPricing",
    "MusicModelPricing",
    "ModelConstraints",
    "ModelPricing",
    "ModelDeprecation",
    "ModelSpec",
    "TextModelSpec",
    "ImageModelSpec",
    "VideoModelSpec",
    "InpaintModelSpec",
    "MusicModelSpec",
    "TtsModelSpec",
    "AsrModelSpec",
    "EmbeddingModelSpec",
    "UpscaleModelSpec",
    "ModelResponse",
    "ModelsListResponse",
    "ModelTraitsResponse",
    "ModelCompatibilityResponse",
    # From api_keys module
    "ConsumptionLimits",
    "TrailingSevenDaysUsage",
    "ApiKeyUsage",
    "ApiKey",
    "ApiKeysListResponse",
    "CreatedApiKey",
    "CreateApiKeyResponse",
    "DeleteApiKeyResponse",
    "ApiKeyDetailsResponse",
    "RateLimit",
    "ModelRateLimit",
    "ApiTier",
    "Balances",
    "RateLimitsData",
    "RateLimitsResponse",
    "RateLimitLogEntry",
    "RateLimitType",
    "RateLimitLogsResponse",
    # From billing module
    "InferenceDetails",
    "BillingUsageEntry",
    "BillingUsageHistoryResponse",
    "BillingBalanceResponse",
    # From billing module - Usage Analytics (Beta)
    "UsageAnalyticsByDate",
    "UsageAnalyticsModelBreakdown",
    "UsageAnalyticsByModel",
    "UsageAnalyticsByKey",
    "UsageAnalyticsResponse",
    "UsageAnalyticsQueryParams",
    # From audio module
    "ClonedVoice",
    "VoiceDetail",
    "VoiceList",
    "AudioResponse",
    "TranscriptionWord",
    "AudioTranscriptionResponse",
    # From augment module
    "AugmentScrapeRequest",
    "AugmentScrapeResponse",
    "AugmentSearchRequest",
    "AugmentSearchResult",
    "AugmentSearchResponse",
    "AugmentTextParserResponse",
    # From crypto module
    "BatchJsonRpcResponse",
    "CryptoNetworksResponse",
    "JsonRpcError",
    "JsonRpcRequest",
    "JsonRpcResponse",
    # From x402 module
    "X402BalanceData",
    "X402BalanceResponse",
    "X402TopUpData",
    "X402TopUpResponse",
    "X402Transaction",
    "X402TransactionsData",
    "X402TransactionsPagination",
    "X402TransactionsResponse",
    # From embeddings module
    "EmbeddingObject",
    "EmbeddingUsage",
    "EmbeddingsResponse",
    # From characters module
    "CharacterStats",
    "Character",
    "CharactersListResponse",
    "CharacterResponse",
    "CharacterReview",
    "CharacterReviewsPagination",
    "CharacterReviewsSummary",
    "CharacterReviewsResponse",
    # From web3 module
    "Web3TokenData",
    "Web3TokenResponse",
    "Web3ApiKeyResponse",
    # From streaming module
    "ChunkModelFactory",
    "ChatCompletionTopLogprob",
    "ChatCompletionTokenLogprob",
    "ChatCompletionChoiceLogprobs",
    "ChatCompletionChunkToolCallFunction",
    "ChatCompletionChunkToolCall",
    "ChatCompletionChunkChoiceDelta",
    "ChatCompletionChunkChoice",
    "ChatCompletionChunk",
    # From requests module - Chat completion models
    "TextContent",
    "ImageUrl",
    "ImageContent",
    "FileObject",
    "FileContent",
    "UserMessage",
    "AssistantMessage",
    "ToolMessage",
    "SystemMessage",
    "ChatMessageParam",
    "DeveloperMessage",
    "StreamOptions",
    "ToolFunction",
    "Tool",
    "ToolChoiceFunction",
    "SpecificToolChoice",
    "JSONSchemaFormat",
    "JSONObjectFormat",
    "TextResponseFormat",
    "VeniceParameters",
    "ReasoningEffortLevel",
    "ReasoningSummary",
    "ReasoningConfig",
    "ChatCompletionRequest",
    # From requests module - Responses API (Alpha)
    "ResponsesRequest",
    # From responses module - Responses API (Alpha)
    "ResponsesError",
    "ResponsesFunctionCallOutput",
    "ResponsesMessageOutput",
    "ResponsesOutputItem",
    "ResponsesOutputText",
    "ResponsesReasoningOutput",
    "ResponsesResponse",
    "ResponsesStreamEvent",
    "ResponsesUnknownOutput",
    "ResponsesUsage",
    "ResponsesUsageInputDetails",
    "ResponsesUsageOutputDetails",
    "ResponsesWebSearchCallOutput",
    # From requests module - Image generation models
    "ImageGenerationRequest",
    "SimpleImageGenerationRequest",
    "ImageUpscaleRequest",
    "StyleReference",
    "ImageEditRequest",
    "ImageBackgroundRemoveRequest",
    "ImageMultiEditRequest",
    # From requests module - Audio models
    "AudioSpeechRequest",
    "AudioTranscriptionRequest",
    # From requests module - Embeddings models
    "EmbeddingsRequest",
    # From requests module - API key models
    "ConsumptionLimit",
    "CreateApiKeyRequest",
    "UpdateApiKeyRequest",
    "Web3CreateApiKeyRequest",
    # From requests module - Query parameter models
    "ModelsQueryParams",
    "ModelTraitsQueryParams",
    "BillingUsageHistoryQueryParams",
    "DeleteApiKeyQueryParams",
    # From requests module - Utility models
    "PaginationParams",
    "DateRangeParams",
    # From video module - Response models
    "VideoQueueResponse",
    "VideoQuoteResponse",
    "VideoProcessingStatus",
    "VideoFailedStatus",
    "VideoCompletedStatus",
    "VideoCompleteResponse",
    "VideoRetrieveResponse",
    "VideoTranscriptionResponse",
    # From requests module - Video request models
    "VideoRequestBase",
    "VideoConsents",
    "SeedanceConsents",
    "VideoTextToVideoRequest",
    "VideoImageToVideoRequest",
    "VideoQueueRequest",
    "VideoQuoteRequest",
    "VideoRetrieveRequest",
    "VideoCompleteRequest",
    "VideoTranscriptionRequest",
    # From music module - Response models
    "MusicQueueResponse",
    "MusicQuoteResponse",
    "MusicProcessingStatus",
    "MusicFailedStatus",
    "MusicCompletedStatus",
    "MusicCompleteResponse",
    "MusicRetrieveResponse",
    # From requests module - Music request models
    "MusicQueueRequest",
    "MusicQuoteRequest",
    "MusicRetrieveRequest",
    "MusicCompleteRequest",
]
