"""
Embeddings models for Venice AI API.

This module contains Pydantic models for text embedding requests and responses.
"""

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from ...core.models.common import VeniceBaseModel


class EmbeddingObject(BaseModel):
    """Individual embedding object"""

    model_config = ConfigDict(extra="allow")

    object: Literal["embedding"] = Field(..., description="Always 'embedding'")
    index: int = Field(..., description="Index of this embedding in the input array")
    embedding: list[float] | str = Field(
        ...,
        description="Vector of floating-point numbers or base64-encoded string representing the embedding",
    )
    encoding_format: Literal["float", "base64"] | None = Field(
        default=None, description="Format of the embedding data"
    )


class EmbeddingUsage(BaseModel):
    """Embedding usage information"""

    model_config = ConfigDict(extra="allow")

    prompt_tokens: int = Field(..., description="Number of tokens in the input")
    total_tokens: int = Field(..., description="Total tokens processed")


class EmbeddingsResponse(VeniceBaseModel):
    """Embeddings endpoint response"""

    model_config = ConfigDict(extra="allow")

    object: Literal["list"] = Field(..., description="Always 'list'")
    model: str = Field(..., description="Model used to generate embeddings")
    data: list[EmbeddingObject] = Field(
        ..., description="The list of embeddings generated by the model"
    )
    usage: EmbeddingUsage = Field(..., description="Usage information for the request")
    id: str | None = Field(default=None, description="Response identifier")
    created: int | None = Field(
        default=None, description="Unix timestamp (seconds) when the response was created"
    )


__all__ = [
    "EmbeddingObject",
    "EmbeddingUsage",
    "EmbeddingsResponse",
]
